version: '3.8'

services:
  admin-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-service-docker
    restart: unless-stopped
    ports:
      - '3010:3010'
    environment:
      - NODE_ENV=development
      - PORT=3010
      - HOST=0.0.0.0
      - JWT_SECRET=admin_service_jwt_dev_secret_123
      - USER_SERVICE_URL=http://host.docker.internal:3002
      - USER_SERVICE_SECRET=admin_user_service_secret_dev
      - LOG_LEVEL=debug
      - CORS_ORIGIN=http://localhost:3000,http://localhost:4000
    volumes:
      - ./logs:/app/logs
    networks:
      - admin-network
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3010/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  admin-network:
    driver: bridge
